// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240327075922_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.UsersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "fszymanowski0@com.com",
                            FirstName = "Fawnia",
                            LastName = "Szymanowski",
                            Password = "74a14ea74c47ecdf30f940974dc9dc20",
                            PhoneNumber = "0335487991",
                            UserName = "fszymanowski0"
                        },
                        new
                        {
                            Id = 2,
                            Email = "apeacocke1@google.ca",
                            FirstName = "Fawnia",
                            LastName = "Alexandros",
                            Password = "c52c635d98738ff357b13d9e4368aff6",
                            PhoneNumber = "0354579415",
                            UserName = "apeacocke1"
                        },
                        new
                        {
                            Id = 3,
                            Email = "cpancoast2@wsj.com",
                            FirstName = "Cazzie",
                            LastName = "Pancoast",
                            Password = "7f45928bce3ba52d77dee0cf1a8bbfdf",
                            PhoneNumber = "0354596415",
                            UserName = "cpancoast2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
